name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint code
        run: |
          flake8 .
          black --check .

      - name: Run tests
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t my-inventory-system .

      - name: Test Docker container
        run: |
          docker run --rm my-inventory-system python manage.py test
